### ISSUE TITLE
M1 : License

### ISSUE THREAD

**Issue by malov** [matruss/decanter#1]
What do we want to use ? The only true contenders imho are Apache 2.0, MIT or BSD. GPL is too restrictive potentially.

**Comment by malov** [comment]
Opinions ? Say, @andry1  we have it available and you decide to use, how would you prefer it'd be licensed ?

**Comment by btrofimov** [comment]
I would prefer to the direct mentionig our project somewhere :) From this perspective MIT is nice option.

**Comment by malov** [comment]
Not that I against MIT license, but how would mentioning our project is related to it ?

**Comment by btrofimov** [comment]
I would prefer if for instance call it "Google" start using our library then it must explicitly specify that fact

**Comment by malov** [comment]
All right, don't have anything against it. I'd think that it would be possible to use it everywhere. All agreed ?

**Comment by malov** [comment]
MIT then.
