### ISSUE TITLE
M1 : Project name

### ISSUE THREAD

**Issue by malov** [matruss/decanter#3]
I'm kinda struggling with it. Old name is out of option, "anvil" is something used for forging other stuff, and that's what we want, right ?

**Comment by malov** [comment]
All right @btrofimov @nshmatko @andry1 : what would you suggest as an alternative to Sibyl ? Don't want to cause any unwanted association for occasional visitors.

**Comment by andry1** [comment]
I'm struggling to come up with anything more creative at the moment, "anvil" isn't already taken? :)  FWIW I always thought of it more as pouring things into a big bucket rather than forging other stuff, but 'bucket' is kind of a boring name

**Comment by malov** [comment]
Mmm, ok. Decanter ? Growler ? Pitcher ?

**Comment by malov** [comment]
I actually like _Decanter_. I poured yesterday Bordeaux with it, and it worked really well :)

**Comment by andry1** [comment]
+1

**Comment by nshmatko** [comment]
Carafe? :stuck_out_tongue_winking_eye:

**Comment by malov** [comment]
Mmm, we have a tie ... Probably need to get Taras to have an odd number of voters :)

**Comment by nshmatko** [comment]
@taraspogrebniak Your turn :smile:

**Comment by malov** [comment]
http://www.waterford.co.uk/lismore-ships-decanter

Doesn't it look gorgeous @taraspogrebniak ? :)

**Comment by taraspogrebniak** [comment]
@malov it does :) `Decanter` sounds fine for me

**Comment by nshmatko** [comment]
@malov Your image works good for Java. Since we're going to use Scala the following should be our choice :satisfied: http://mecsoft.com/blog/wp-content/uploads/2014/03/Carafes.png

**Comment by malov** [comment]
Are you kidding me @nshmatko ? Of course _Decanter_ is more scalish ! Besides, Taras voted and you both lost :stuck_out_tongue_winking_eye:
