### ISSUE TITLE
M1 : Coding standards

### ISSUE THREAD

**Issue by malov** [matruss/decanter#5]
Since we are tiny group of people knowing each other very well, we could agree on some coding principals to follow. I think ?

**Comment by btrofimov** [comment]
What we did before is close to Data Brick's Scala convention so it might be kind of golden standard for us https://github.com/databricks/scala-style-guide

**Comment by malov** [comment]
Haven't read it in full before, there are a quite few things I disagree with, some of them : 
- I'd stick with naming constants in _CamelCase_
- Calling by name could be very powerful, though it's certainly an advance feature
- Same note about implicits
- Same about curring
- While _while_ and _for_ loops are faster than _map_ etc, in practice it usually doesn't matter, as IO and network bandwidth cause much more performance grief. Plus, I think they much better optimized in later Scala versions.

Style-wise, the only thing which truly matters, is using spaces for indentation and not tabs. Otherwise code could look truly horrible.

**Comment by malov** [comment]
Coding standards from [Twitter](http://twitter.github.io/effectivescala/) are much more to my liking. But again, I don't think we should impose something additional and strict on ourselves, as we know each other's coding very well.

**Comment by btrofimov** [comment]
I agree with you. Actually they do not conflict to each other. Codebreaks  is more about code style convention, there is checkstyle xml file to support them and we can easily add to sbt project. Looks like Twitter's version is more about best practicies.

**Comment by malov** [comment]
Do we want scalastyle.xml, in a simplest form, at least ? Just asking.

**Comment by taraspogrebniak** [comment]
I think `scalastyle.xml` makes sense

**Comment by malov** [comment]
Settled then :)
