### ISSUE TITLE
M1 : Initial target

### ISSUE THREAD

**Issue by malov** [matruss/decanter#6]
What do we want to achieve first, what should be our foundation we want to build upon ?

**Comment by btrofimov** [comment]
I am voting for s3 and sftp as well. The first version might be just downloader to hdfs. That what I need too btw :)

**Comment by malov** [comment]
So, how we define our first target ? source -> sftp -> hdfs ?

**Comment by taraspogrebniak** [comment]
speaking about the first version, are we going to implement `sftp -> hdfs` or `hdfs -> sftp` as well?

**Comment by malov** [comment]
Sounds reasonable to me.

**Comment by malov** [comment]
Since nobody has any new ideas, declare it's decided.
